var config = {
  backgroundImages:[
      "https://i.imgur.com/mE1MUpd.jpeg",
      "https://i.imgur.com/nR8jJEM.jpeg",
      "https://flic.kr/p/2241jmw",
      "https://flic.kr/p/SW9qPb",
  ],
  widgets:[
    {
      widget:"GRTbus",
      data:{stop:"5008"}
    },
    {
      widget:"Status",
      data:{url:"https://example.com/status.txt"}
    },
    {
      widget:"Weather",
      data:{appid:"xxxxxxxxx",city:"Waterloo"}
    }
  ]
};
